// Code generated by ent, DO NOT EDIT.

package ent

import (
	"auto-trader/ent/predicate"
	"auto-trader/ent/strategyperformance"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StrategyPerformanceDelete is the builder for deleting a StrategyPerformance entity.
type StrategyPerformanceDelete struct {
	config
	hooks    []Hook
	mutation *StrategyPerformanceMutation
}

// Where appends a list predicates to the StrategyPerformanceDelete builder.
func (_d *StrategyPerformanceDelete) Where(ps ...predicate.StrategyPerformance) *StrategyPerformanceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StrategyPerformanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StrategyPerformanceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StrategyPerformanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(strategyperformance.Table, sqlgraph.NewFieldSpec(strategyperformance.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StrategyPerformanceDeleteOne is the builder for deleting a single StrategyPerformance entity.
type StrategyPerformanceDeleteOne struct {
	_d *StrategyPerformanceDelete
}

// Where appends a list predicates to the StrategyPerformanceDelete builder.
func (_d *StrategyPerformanceDeleteOne) Where(ps ...predicate.StrategyPerformance) *StrategyPerformanceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StrategyPerformanceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{strategyperformance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StrategyPerformanceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
