// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Portfolio is the predicate function for portfolio builders.
type Portfolio func(*sql.Selector)

// Strategy is the predicate function for strategy builders.
type Strategy func(*sql.Selector)

// StrategyExecution is the predicate function for strategyexecution builders.
type StrategyExecution func(*sql.Selector)

// StrategyPerformance is the predicate function for strategyperformance builders.
type StrategyPerformance func(*sql.Selector)

// StrategyStatus is the predicate function for strategystatus builders.
type StrategyStatus func(*sql.Selector)

// StrategyTemplate is the predicate function for strategytemplate builders.
type StrategyTemplate func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
